routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Customer\CheckoutController;
use App\Http\Controllers\Customer\ProfileController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MenuCategoryController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\PesananController;
use Doctrine\DBAL\Schema\Index;
use GuzzleHttp\Psr7\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('admin-page', function() {
//     return '';
// })->middleware('role:admin')->name('admin.page');

// Route::get('user-page', function() {
//     return 'Halaman untuk User';
// })->middleware('role:user')->name('user.page');
Route::get('/cart', function () {
    return view('cart');
});
// Route::get('/login', function () {
    Route::get('/login', function() {
    return redirect()->route('login');
});
// Route::post('/register', [RegisterController::class, 'create'])->name('register');
// Route::get('/register', function() {
    //     return view('auth.register');
    // });

    Route::get('/resetpassword', [ResetPasswordController::class, 'index'])->name('reset.password');
    Route::put('/resetpassword', [ResetPasswordController::class, 'update'])->name('reset.update');

    // Route::get('/', [CustomerController::class, 'index'])->name('landingPage');

    //Guest
    Route::get('/', [CustomerController::class, 'index']);
    Route::get('product/detail/{id}', [CustomerController::class, 'show'])->name('detail.product');
    // Route::get('customer/cart', [CartController::class, 'index'])->name('cart');


    Auth::routes();
    Route::group(['prefix'=>'admin/','as'=>'admin.'], function(){
        Route::middleware('role:admin')->group(function (){
            Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::resource('user', UserController::class);
            Route::resource('categories', MenuCategoryController::class);
            Route::resource('product', ProductController::class);
            Route::get('reportorder', [ReportController::class, 'reportorder'])->name('reportorder');
            Route::get('exportorder', [ReportController::class, 'reportorder'])->name('exportorder');
            Route::get('reportproduct', [ReportController::class, 'reportproduct'])->name('reportproduct');
            Route::get('exportproduct', [ReportController::class, 'reportproductexport'])->name('exportproduct');
            Route::get('reportuser', [ReportController::class, 'reportuser'])->name('reportuser');
            Route::get('exportuser', [ReportController::class, 'reportuserexport'])->name('exportuser');
            Route::get('list', [OrderController::class, 'index'])->name('order');
            Route::get('list/detail/{id}', [OrderController::class, 'show'])->name('orderdetail');
            Route::get('grafik', [ChartController::class, 'index'])->name('grafik.barchart');
            Route::get('list/create', [OrderController::class, 'create'])->name('ordercreate');
        });
    });

    Route::group(['prefix'=>'user/', 'as'=>'user.'], function(){
        Route::middleware('role:user')->group(function () {
            Route::get('/', [CustomerController::class, 'index']);
            Route::get('customer', [ProfileController::class, 'index'])->name('index');
            Route::get('customer/edit/{id}', [ProfileController::class, 'edit'])->name('edit');
            Route::put('customer/update/{id}', [ProfileController::class, 'update'])->name('update');
            Route::get('customer/cart', [CartController::class, 'index'])->name('cart');
            Route::post('customer/cart', [CartController::class, 'store'])->name('cart.store');
            Route::get('customer/checkout', [CheckoutController::class, 'index'])->name('checkout');
            Route::get('customer/details/{id}', [DetailController::class, 'show'])->name('details');
    });
    Route::get('customer/pesanan', [PesananController::class, 'index'])->name('pesanan');
    });

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ReportOrderExport;
use App\Exports\ReportOrderUserExport;
use App\Exports\ReportProductExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function reportorder()
    {
        return view('pages.admin.report.order');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function reportproduct()
    {
        $orders = Order::all();
        return view('pages.admin.report.product', compact('orders'));
    }

    public function reportproductexport(){
        return Excel::download(new ReportProductExport, 'ReportProduct.xlsx');
    }

    public function reportuser()
    {
        $orders = Order::all();
        return view('pages.admin.report.user', compact('orders'));
    }

    public function reportuserexport(){
        return Excel::download(new ReportOrderUserExport, 'Reportuser.xlsx');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/report/order.blade.php
@extends('layouts.admin.app')
@section('content')
<div class="card-header border-0 py-5">
    <h3 class="card-title align-items-start flex-column">
        <span class="card-label font-weight-bolder text-dark">Data Penjualan</span>
    </h3>
    <div class="col-md-12">
        <div class="form-group row">
            <div class="col-sm-2-ml-1">
                <label for="from" class="col-form-label">Date From:</label>
            </div>
            <div class="col-sm-3">
                <input type="date" class="form-control input-sm w-100" id="from" name="from"  required>
            </div>
            <div class="col-sm-2-ml-1">
                <label for="to" class="col-form-label ">Date to:</label>
            </div>
            <div class="col-sm-3">
                <input type="date" class="form-control input-sm w-100" id="to" name="to" required>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-primary"><i class="flaticon-search-magnifier-interface-symbol"></i></button>
                <a href="{{ route('admin.exportorder') }}" class="btn btn-primary"><i class="flaticon-technology ml-1"></i></a>
            </div>
        </div>
    </div>
</div>
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 20px">No</th>
                            <th style="min-width: 80px">Tgl</th>
                            <th style="min-width: 100px">Nama Customer</th>
                            <th style="min-width: 100px">Nama Produk</th>
                            <th style="min-width: 100px">Categori</th>
                            <th style="min-width: 50px">Pesanan</th>
                            <th style="min-width: 50px">Jumlah Terjual</th>
                            <th style="min-width: 100px">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center align-items-center flex-wrap">
                <div class="d-flex flex-wrap mr-3">
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-back icon-xs"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary active mr-2 my-1">1</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">2</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">3</a>
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-next icon-xs"></i>
                    </a>
                </div>
            </div>
            <!--end::Table-->
        </div>
    </div>
@stop

resources/views/pages/admin/report/product.blade.php
@extends('layouts.admin.app')
@section('content')
<div class="card-header border-0 py-5">
    <h3 class="card-title align-items-start flex-column">
        <span class="card-label font-weight-bolder text-dark">Order By Product</span>
    </h3>
    <div class="col-md-12">
        <div class="form-group row">
            <div class="col-sm-2-ml-1">
                <label for="from" class="col-form-label">Date From:</label>
            </div>
            <div class="col-sm-3">
                <input type="date" class="form-control input-sm w-100" id="from" name="from"  required>
            </div>
            <div class="col-sm-2-ml-1">
                <label for="to" class="col-form-label ">Date to:</label>
            </div>
            <div class="col-sm-3">
                <input type="date" class="form-control input-sm w-100" id="to" name="to" required>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-primary"><i class="flaticon-search-magnifier-interface-symbol"></i></button>
                <a href="{{ route('admin.exportproduct') }}" class="btn btn-primary"><i class="flaticon-technology ml-1"></i></a>
            </div>
        </div>
    </div>
</div>
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 20px">No</th>
                            <th style="min-width: 80px">Tgl</th>
                            <th style="min-width: 100px">Nama Customer</th>
                            <th style="min-width: 100px">Nama Produk</th>
                            <th style="min-width: 100px">Categori</th>
                            <th style="min-width: 50px">Pesanan</th>
                            <th style="min-width: 50px">Jumlah Terjual</th>
                            <th style="min-width: 100px">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($orders as $data )
                            <tr>
                                <td>{{$data->id}}</td>
                                <td>{{$data->order_date}}</td>
                                <td>{{$data->user_id}}</td>
                                <td>{{$data->status}}</td>
                                <td>{{$data->proof_of_payment}}</td>
                                <td>{{$data->order_number}}</td>
                                <td>{{$data->order_number}}</td>
                                <td>{{$data->total}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center align-items-center flex-wrap">
                <div class="d-flex flex-wrap mr-3">
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-back icon-xs"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary active mr-2 my-1">1</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">2</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">3</a>
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-next icon-xs"></i>
                    </a>
                </div>
            </div>
            <!--end::Table-->
        </div>
    </div>
@stop

resources/views/pages/admin/report/user.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card-header border-0 py-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label font-weight-bolder text-dark">Order By User</span>
        </h3>
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-sm-2-ml-1">
                    <label for="from" class="col-form-label">Date From:</label>
                </div>
                <div class="col-sm-3">
                    <input type="date" class="form-control input-sm w-100" id="from" name="from"  required>
                </div>
                <div class="col-sm-2-ml-1">
                    <label for="to" class="col-form-label ">Date to:</label>
                </div>
                <div class="col-sm-3">
                    <input type="date" class="form-control input-sm w-100" id="to" name="to" required>
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-primary"><i class="flaticon-search-magnifier-interface-symbol"></i></button>
                    <a href="{{ route('admin.exportuser') }}" class="btn btn-primary"><i class="flaticon-technology ml-1"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 20px">No</th>
                            <th style="min-width: 80px">Tgl</th>
                            <th style="min-width: 100px">Nama Customer</th>
                            <th style="min-width: 100px">Nama Produk</th>
                            <th style="min-width: 100px">Categori</th>
                            <th style="min-width: 50px">Pesanan</th>
                            <th style="min-width: 50px">Jumlah Terjual</th>
                            <th style="min-width: 100px">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($orders as $data)
                            <tr>
                                <td>{{$data->id}}</td>
                                <td>{{$data->order_date}}</td>
                                <td>{{$data->user_id}}</td>
                                <td>{{$data->status}}</td>
                                <td>{{$data->proof_of_payment}}</td>
                                <td>{{$data->order_number}}</td>
                                <td>{{$data->order_number}}</td>
                                <td>{{$data->total}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center align-items-center flex-wrap">
                <div class="d-flex flex-wrap mr-3">
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-back icon-xs"></i>
                    </a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary active mr-2 my-1">1</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">2</a>
                    <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">3</a>
                    <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                        <i class="ki ki-bold-arrow-next icon-xs"></i>
                    </a>
                </div>
            </div>
            <!--end::Table-->
        </div>
    </div>
@stop