routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Customer\CheckoutController;
use App\Http\Controllers\Customer\ProfileController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MenuCategoryController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\PesananController;
use Doctrine\DBAL\Schema\Index;
use GuzzleHttp\Psr7\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('admin-page', function() {
//     return '';
// })->middleware('role:admin')->name('admin.page');

// Route::get('user-page', function() {
//     return 'Halaman untuk User';
// })->middleware('role:user')->name('user.page');
Route::get('/cart', function () {
    return view('cart');
});
// Route::get('/login', function () {
    Route::get('/login', function() {
    return redirect()->route('login');
});
// Route::post('/register', [RegisterController::class, 'create'])->name('register');
// Route::get('/register', function() {
    //     return view('auth.register');
    // });

    Route::get('/resetpassword', [ResetPasswordController::class, 'index'])->name('reset.password');
    Route::put('/resetpassword', [ResetPasswordController::class, 'update'])->name('reset.update');

    // Route::get('/', [CustomerController::class, 'index'])->name('landingPage');

    //Guest
    Route::get('/', [CustomerController::class, 'index']);
    Route::get('product/detail/{id}', [CustomerController::class, 'show'])->name('detail.product');
    // Route::get('customer/cart', [CartController::class, 'index'])->name('cart');


    Auth::routes();
    Route::group(['prefix'=>'admin/','as'=>'admin.'], function(){
        Route::middleware('role:admin')->group(function (){
            Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::resource('user', UserController::class);
            Route::resource('categories', MenuCategoryController::class);
            Route::resource('product', ProductController::class);
            Route::get('reportorder', [ReportController::class, 'reportorder'])->name('reportorder');
            Route::get('exportorder', [ReportController::class, 'reportorder'])->name('exportorder');
            Route::get('reportproduct', [ReportController::class, 'reportproduct'])->name('reportproduct');
            Route::get('exportproduct', [ReportController::class, 'reportproductexport'])->name('exportproduct');
            Route::get('reportuser', [ReportController::class, 'reportuser'])->name('reportuser');
            Route::get('exportuser', [ReportController::class, 'reportuserexport'])->name('exportuser');
            Route::get('list', [OrderController::class, 'index'])->name('order');
            Route::get('list/detail/{id}', [OrderController::class, 'show'])->name('orderdetail');
            Route::get('grafik', [ChartController::class, 'index'])->name('grafik.barchart');
            Route::get('list/create', [OrderController::class, 'create'])->name('ordercreate');
        });
    });

    Route::group(['prefix'=>'user/', 'as'=>'user.'], function(){
        Route::middleware('role:user')->group(function () {
            Route::get('/', [CustomerController::class, 'index']);
            Route::get('customer', [ProfileController::class, 'index'])->name('index');
            Route::get('customer/edit/{id}', [ProfileController::class, 'edit'])->name('edit');
            Route::put('customer/update/{id}', [ProfileController::class, 'update'])->name('update');
            Route::get('customer/cart', [CartController::class, 'index'])->name('cart');
            Route::post('customer/cart', [CartController::class, 'store'])->name('cart.store');
            Route::get('customer/checkout', [CheckoutController::class, 'index'])->name('checkout');
            Route::get('customer/details/{id}', [DetailController::class, 'show'])->name('details');
    });
    Route::get('customer/pesanan', [PesananController::class, 'index'])->name('pesanan');
    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    protected $fillable = [
        'menu_category_id',
        'name',
        'price',
        'stock',
        'description',
        'image',
        'unit',
    ];

    use SoftDeletes;
    protected $dates = ['deleted_at'];

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\MenuCategory;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $menu_categories = MenuCategory::get();
        return view ('pages.admin.product.index', compact('products', 'menu_categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $menu_categories = MenuCategory::get();
        return view ('pages.admin.product.create', compact('menu_categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'menu_category_id' => 'required',
            'name' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'description' => 'required',
            'unit' => 'required',
        ]);

        $input = $request->all();
        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHis').'.'.$file->getClientOriginalExtension();
            $file-> move(public_path('/image'), $filename);
            $input['image']= $filename;
        }

        $result = Product::create($input);


        if ($result) return redirect()->route('admin.product.index')->with('success', 'Berhasil Menyimpan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findorfail($id);
        $menu_categories = MenuCategory::get();
        return view ('pages.admin.product.edit', compact('menu_categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findorfail($id);
        $input = $request->all();

        $product->update($input);
        return redirect()->route('admin.product.index')->with('success', 'Berhasil Menyimpan !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('admin.product.index')->with('success', 'Berhasil Hapus !');
    }
}

resources/views/pages/admin/product/create.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Base Controls
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.product.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="mb-3">
                        <label for="image" class="form-label">Post Image</label>
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image" name="image" required>
                        @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Category <span class="text-danger">*</span></label>
                        <select name="menu_category_id" class="form-control">
                            <option value="" disabled selected>Choose Category</option>
                            @foreach ($menu_categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category_id')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Name <span class="text-danger">*</span></label>
                        <input name="name" type="text" class="form-control" placeholder="Enter name" />
                        @error('name')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Price <span class="text-danger">*</span></label>
                        <input name="price" type="number" class="form-control" placeholder="Enter price" />
                        @error('price')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Stock <span class="text-danger">*</span></label>
                        <input name="stock" type="number" class="form-control" placeholder="Enter stok" />
                        @error('stock')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Description <span class="text-danger">*</span></label>
                        <input name="description" type="text" class="form-control" placeholder="Enter description" />
                        @error('description')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Unit <span class="text-danger">*</span></label>
                        <input name="unit" type="text" class="form-control" placeholder="Enter unit" />
                        @error('unit')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-secondary" href="{{ Route('admin.product.index') }}">Cancel</a>
                </div>
        </form>
        <!--end::Form-->
    </div>
@endsection

resources/views/pages/admin/product/edit.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Base Controls
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.product.update', $product->id) }}" method="post">
            @csrf
            @method('put')
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="mb-3">
                        <label for="image" class="form-label">Post Image</label>
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image"
                            name="image" value="{{asset('image/'.$product   ->image) }}">
                        @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Category <span class="text-danger">*</span></label>
                        <select name="menu_category_id" class="form-control">
                            <option value="{{ $product->menu_category_id }}" disabled selected>Choose Category</option>
                            @foreach ($menu_categories as $category)
                                <option value="{{ $category->id }}" {{ $product->menu_category_id == $category->id ? 'selected' : '' }}>Makanan </option>
                            @endforeach
                        </select>
                        @error('category_id')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Name <span class="text-danger">*</span></label>
                        <input name="name" type="text" class="form-control" placeholder="Enter name" value="{{ $product->name }}"/>
                        @error('name')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Price <span class="text-danger">*</span></label>
                        <input name="price" type="number" class="form-control" placeholder="Enter price"  value="{{ $product->price }}"/>
                        @error('price')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Stock <span class="text-danger">*</span></label>
                        <input name="stock" type="number" class="form-control" placeholder="Enter stok"  value="{{ $product->stock }}"/>
                        @error('stock')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Description <span class="text-danger">*</span></label>
                        <input name="description" type="text" class="form-control" placeholder="Enter description"  value="{{ $product->description }}"/>
                        @error('description')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Unit <span class="text-danger">*</span></label>
                        <input name="unit" type="text" class="form-control" placeholder="Enter unit"  value="{{ $product->unit }}"/>
                        @error('description')
                            <span class="form-text text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-secondary" href="{{ Route('admin.product.index') }}">Cancel</a>
                </div>
        </form>
        <!--end::Form-->
    </div>
@endsection

resources/views/pages/admin/product/index.blade.php
@extends('layouts.admin.app')
@section('content')
    {{-- <div>
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nis</th>
            <th>Nama</th>
            <th>Rombel</th>
            <th>Rayon</th>
            <th width="280px">Action</th>
        </tr>
</div> --}}
    <div class="card-header border-0 py-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label font-weight-bolder text-dark">Data Product</span>
        </h3>
        <div class="card-toolbar">
            <a href="{{ route('admin.product.create') }}" class="btn btn-success font-weight-bolder font-size-sm">Create</a>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 100px">Image</th>
                            <th style="min-width: 100px">Category</th>
                            <th style="min-width: 100px">Name</th>
                            <th style="min-width: 100px">Price</th>
                            <th style="min-width: 100px">Stock</th>
                            <th style="min-width: 100px">Decription</th>
                            <th style="min-width: 100px">Unit</th>
                            <th style="min-width: 100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $data)
                            <tr>
                                <td><img src="{{ asset('image/'.$data->image) }}" class="card-img" height="100" alt="" /></td>
                                <td>{{ $data->menu_category_id }}</td>
                                <td>{{ $data->name }}</td>
                                <td>{{ $data->price }}</td>
                                <td>{{ $data->stock }}</td>
                                <td>{{ $data->description }}</td>
                                <td>{{ $data->unit }}</td>
                                <td>
                                    <div class="row">
                                        <div class="col-6">
                                            <a class="btn btn-primary"
                                                href="{{ route('admin.product.edit', $data) }}">Edit</a>
                                        </div>
                                        <div class="col-6">
                                            <form action="{{ route('admin.product.destroy', $data) }}" method="POST"
                                                class="d-inline">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!--end::Table-->
        </div>
    </div>
    {{-- <div class="card card-custom">
    <div class="card-header">
     <h3 class="card-title">
      Textual HTML5 Inputs
     </h3>
    </div>
    <!--begin::Form-->
    <form>
     <div class="card-body">
      <div class="form-group mb-8">
      <div class="form-group row">
       <label  class="col-2 col-form-label">Name</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-text-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-search-input" class="col-2 col-form-label">Email</label>
       <div class="col-10">
        <input class="form-control" type="search" id="example-search-input"/>
       </div>
      </div>
      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Password</label>
        <div class="col-10">
         <input class="form-control" type="password" id="example-password-input"/>
        </div>
       </div>
      <div class="form-group row">
       <label for="example-tel-input" class="col-2 col-form-label">Phone</label>
       <div class="col-10">
        <input class="form-control" type="tel" id="example-tel-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-password-input" class="col-2 col-form-label">Address</label>
       <div class="col-10">
        <input class="form-control" type="password"id="example-password-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-date-input" class="col-2 col-form-label">Birth Date</label>
       <div class="col-10">
        <input class="form-control" type="date" id="example-date-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-month-input" class="col-2 col-form-label">Birth Place</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-month-input"/>
       </div>
      </div>
     </div>
     <div class="card-footer">
      <div class="row">
       <div class="col-2">
       </div>
       <div class="col-10">
        <button type="reset" class="btn btn-success mr-2">Submit</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
       </div>
      </div>
     </div>
    </form>
   </div>
</div> --}}
@stop