routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Customer\CheckoutController;
use App\Http\Controllers\Customer\ProfileController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MenuCategoryController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\PesananController;
use Doctrine\DBAL\Schema\Index;
use GuzzleHttp\Psr7\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('admin-page', function() {
//     return '';
// })->middleware('role:admin')->name('admin.page');

// Route::get('user-page', function() {
//     return 'Halaman untuk User';
// })->middleware('role:user')->name('user.page');
Route::get('/cart', function () {
    return view('cart');
});
// Route::get('/login', function () {
    Route::get('/login', function() {
    return redirect()->route('login');
});
// Route::post('/register', [RegisterController::class, 'create'])->name('register');
// Route::get('/register', function() {
    //     return view('auth.register');
    // });

    Route::get('/resetpassword', [ResetPasswordController::class, 'index'])->name('reset.password');
    Route::put('/resetpassword', [ResetPasswordController::class, 'update'])->name('reset.update');

    // Route::get('/', [CustomerController::class, 'index'])->name('landingPage');

    //Guest
    Route::get('/', [CustomerController::class, 'index']);
    Route::get('product/detail/{id}', [CustomerController::class, 'show'])->name('detail.product');
    // Route::get('customer/cart', [CartController::class, 'index'])->name('cart');


    Auth::routes();
    Route::group(['prefix'=>'admin/','as'=>'admin.'], function(){
        Route::middleware('role:admin')->group(function (){
            Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::resource('user', UserController::class);
            Route::resource('categories', MenuCategoryController::class);
            Route::resource('product', ProductController::class);
            Route::get('reportorder', [ReportController::class, 'reportorder'])->name('reportorder');
            Route::get('exportorder', [ReportController::class, 'reportorder'])->name('exportorder');
            Route::get('reportproduct', [ReportController::class, 'reportproduct'])->name('reportproduct');
            Route::get('exportproduct', [ReportController::class, 'reportproductexport'])->name('exportproduct');
            Route::get('reportuser', [ReportController::class, 'reportuser'])->name('reportuser');
            Route::get('exportuser', [ReportController::class, 'reportuserexport'])->name('exportuser');
            Route::get('list', [OrderController::class, 'index'])->name('order');
            Route::get('list/detail/{id}', [OrderController::class, 'show'])->name('orderdetail');
            Route::get('grafik', [ChartController::class, 'index'])->name('grafik.barchart');
            Route::get('list/create', [OrderController::class, 'create'])->name('ordercreate');
        });
    });

    Route::group(['prefix'=>'user/', 'as'=>'user.'], function(){
        Route::middleware('role:user')->group(function () {
            Route::get('/', [CustomerController::class, 'index']);
            Route::get('customer', [ProfileController::class, 'index'])->name('index');
            Route::get('customer/edit/{id}', [ProfileController::class, 'edit'])->name('edit');
            Route::put('customer/update/{id}', [ProfileController::class, 'update'])->name('update');
            Route::get('customer/cart', [CartController::class, 'index'])->name('cart');
            Route::post('customer/cart', [CartController::class, 'store'])->name('cart.store');
            Route::get('customer/checkout', [CheckoutController::class, 'index'])->name('checkout');
            Route::get('customer/details/{id}', [DetailController::class, 'show'])->name('details');
    });
    Route::get('customer/pesanan', [PesananController::class, 'index'])->name('pesanan');
    });

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\controllers;

use App\Models\Categories;
use Illuminate\Http\Request;
use PhpParser\Node\Expr\FuncCall;

class CategoriesController extends Controller
{
    public function index(){
        $categories = Categories::latest()->paginate(5);
        return view('pages.categories.index', compact('categories'));
    }

   public function create(){
    return view('pages.categories.create');
   }

   public function store(Request $request)
   {
       $request->validate([
        'nama' => 'required',
       ]);

       Categories::create($request->all());

       return redirect()->route('admin.categories.index')->with('success', 'Berhasil Menyimpan !');
   }

   public function edit($id)
   {
    $categories = Categories::findorfail($id);
    return view('pages.categories.edit', compact('categories'));
   }

   public function update(Request $request, $id)
   {
    $categories = Categories::findorfail($id);
    $input = $request->all();

    $categories->update($input);

    return redirect()->route('admin.categories.index')->with('success', 'Data Berhasil Di update');
   }

   public function destroy(Categories $categories)
   {
    $categories->delete();

    return redirect()->route('admin.categories.index')->with('success', 'Data Berhasil Di Delete');
   }
}

resources/views/pages/admin/categories/create.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Kategori
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.categories.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class=>
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Post Image</label>
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image"
                            name="image" required>
                        @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Nama<span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="name" placeholder="isi kategori" required />
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                        </div>
                        <div class="card-footer">
                            <button type="sumbit" class="btn btn-primary mr-2">Submit</button>
                            <a class="btn btn-secondary" href="{{ Route('admin.categories.index') }}">Cancel</a>
                        </div>
        </form>
        <!--end::Form-->
    </div>
@endsection

resources/views/pages/admin/categories/edit.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Kategori
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.categories.update', $category->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class=>
                    </div>
                    <div class="form-group">
                        <label>Nama<span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="name" placeholder="isi kategori" required />
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                        </div>
                        <div class="card-footer">
                            <button type="sumbit" class="btn btn-primary mr-2">Update</button>
                            <a class="btn btn-secondary" href="{{ Route('admin.categories.index') }}">Cancel</a>
                        </div>
        </form>
        <!--end::Form-->
    </div>
@endsection

resources/views/pages/admin/categories/index.blade.php
@extends('layouts.admin.app')
@section('content')
    {{-- <div>
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nis</th>
            <th>Nama</th>
            <th>Rombel</th>
            <th>Rayon</th>
            <th width="280px">Action</th>
        </tr>
</div> --}}
    <div class="card-header border-0 py-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label font-weight-bolder text-dark">Kategori</span>
        </h3>
        <div class="card-toolbar">
            <a href="{{ route('admin.categories.create') }}"
                class="btn btn-success font-weight-bolder font-size-sm">Create</a>
        </div>
    </div>
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class=>
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 80px">Image </th>
                            <th style="min-width: 80px">Nama</th>
                            <th style="min-width: 80px">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($categories as $data)
                            <tr>
                                <td><img src="{{ asset('category/'.$data->image) }}" class="card-img" style="width: 110px" alt="" /></td>
                                <td>{{ $data->name }}</td>
                                <td>
                                    <div class="row">
                                        <div class="col-">
                                            <a class="btn btn-primary"
                                                href="{{ route('admin.categories.edit', $data) }}">Edit</a>
                                        </div>
                                        <div class="col-6">
                                            <form action="{{ route('admin.categories.destroy', $data) }}"
                                                method="POST" class="d-inline">
                                                @method('delete')
                                                @csrf
                                                 <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!--end::Table-->
        </div>
    </div>
    {{-- <div class="card card-custom">
    <div class="card-header">
     <h3 class="card-title">
      Textual HTML5 Inputs
     </h3>
    </div>
    <!--begin::Form-->
    <form>
     <div class="card-body">
      <div class="form-group mb-8">
      <div class="form-group row">
       <label  class="col-2 col-form-label">Name</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-text-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-search-input" class="col-2 col-form-label">Email</label>
       <div class="col-10">
        <input class="form-control" type="search" id="example-search-input"/>
       </div>
      </div>
      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Password</label>
        <div class="col-10">
         <input class="form-control" type="password" id="example-password-input"/>
        </div>
       </div>
      <div class="form-group row">
       <label for="example-tel-input" class="col-2 col-form-label">Phone</label>
       <div class="col-10">
        <input class="form-control" type="tel" id="example-tel-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-password-input" class="col-2 col-form-label">Address</label>
       <div class="col-10">
        <input class="form-control" type="password"id="example-password-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-date-input" class="col-2 col-form-label">Birth Date</label>
       <div class="col-10">
        <input class="form-control" type="date" id="example-date-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-month-input" class="col-2 col-form-label">Birth Place</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-month-input"/>
       </div>
      </div>
     </div>
     <div class="card-footer">
      <div class="row">
       <div class="col-2">
       </div>
       <div class="col-10">
        <button type="reset" class="btn btn-success mr-2">Submit</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
       </div>
      </div>
     </div>
    </form>
   </div>
</div> --}}
@stop