routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Customer\CheckoutController;
use App\Http\Controllers\Customer\ProfileController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MenuCategoryController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\PesananController;
use Doctrine\DBAL\Schema\Index;
use GuzzleHttp\Psr7\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('admin-page', function() {
//     return '';
// })->middleware('role:admin')->name('admin.page');

// Route::get('user-page', function() {
//     return 'Halaman untuk User';
// })->middleware('role:user')->name('user.page');
Route::get('/cart', function () {
    return view('cart');
});
// Route::get('/login', function () {
    Route::get('/login', function() {
    return redirect()->route('login');
});
// Route::post('/register', [RegisterController::class, 'create'])->name('register');
// Route::get('/register', function() {
    //     return view('auth.register');
    // });

    Route::get('/resetpassword', [ResetPasswordController::class, 'index'])->name('reset.password');
    Route::put('/resetpassword', [ResetPasswordController::class, 'update'])->name('reset.update');

    // Route::get('/', [CustomerController::class, 'index'])->name('landingPage');

    //Guest
    Route::get('/', [CustomerController::class, 'index']);
    Route::get('product/detail/{id}', [CustomerController::class, 'show'])->name('detail.product');
    // Route::get('customer/cart', [CartController::class, 'index'])->name('cart');


    Auth::routes();
    Route::group(['prefix'=>'admin/','as'=>'admin.'], function(){
        Route::middleware('role:admin')->group(function (){
            Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
            Route::resource('user', UserController::class);
            Route::resource('categories', MenuCategoryController::class);
            Route::resource('product', ProductController::class);
            Route::get('reportorder', [ReportController::class, 'reportorder'])->name('reportorder');
            Route::get('exportorder', [ReportController::class, 'reportorder'])->name('exportorder');
            Route::get('reportproduct', [ReportController::class, 'reportproduct'])->name('reportproduct');
            Route::get('exportproduct', [ReportController::class, 'reportproductexport'])->name('exportproduct');
            Route::get('reportuser', [ReportController::class, 'reportuser'])->name('reportuser');
            Route::get('exportuser', [ReportController::class, 'reportuserexport'])->name('exportuser');
            Route::get('list', [OrderController::class, 'index'])->name('order');
            Route::get('list/detail/{id}', [OrderController::class, 'show'])->name('orderdetail');
            Route::get('grafik', [ChartController::class, 'index'])->name('grafik.barchart');
            Route::get('list/create', [OrderController::class, 'create'])->name('ordercreate');
        });
    });

    Route::group(['prefix'=>'user/', 'as'=>'user.'], function(){
        Route::middleware('role:user')->group(function () {
            Route::get('/', [CustomerController::class, 'index']);
            Route::get('customer', [ProfileController::class, 'index'])->name('index');
            Route::get('customer/edit/{id}', [ProfileController::class, 'edit'])->name('edit');
            Route::put('customer/update/{id}', [ProfileController::class, 'update'])->name('update');
            Route::get('customer/cart', [CartController::class, 'index'])->name('cart');
            Route::post('customer/cart', [CartController::class, 'store'])->name('cart.store');
            Route::get('customer/checkout', [CheckoutController::class, 'index'])->name('checkout');
            Route::get('customer/details/{id}', [DetailController::class, 'show'])->name('details');
    });
    Route::get('customer/pesanan', [PesananController::class, 'index'])->name('pesanan');
    });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use PhpParser\Node\Expr\FuncCall;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'address', 'birth_date', 'birth_place', 'image', 'jk',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function order()
    {
        return $this->hasMany(Order::class);
    }

    public function cart()
    {
        return $this->hasMany(Cart::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use PhpParser\Node\Expr\FuncCall;

class UserController extends Controller
{
    public function index(){
        $users = User::latest()->paginate(7);
        return view('pages.admin.user.index', compact('users'));
    }

   public function create(){
    return view('pages.admin.user.create');
   }

   public function store(Request $request)
   {

    $this->validate($request, [
        'name' => 'required',
        'email' => 'required',
        'password' => 'required',
        'phone' => 'required',
        'address' => 'required',
        'birth_place' => 'required',
        'birth_date' => 'required',
        'jk' => 'requeried',
    ]);

    $input = $request->all();
    if($request->file('image')){
        $file= $request->file('image');
        $filename= date('YmdHis').'.'.$file->getClientOriginalExtension();
        $file-> move(public_path('/image'), $filename);
        $input['image']= $filename;
    }

    $input['password'] = Hash::make($request->password);

    $result = User::create($input);
    $result->assignRole('user');

    if ($result) return redirect()->route('admin.user.index')->with('success', 'Data berhasil di tambahkan');

    return redirect()->back();
   }

   public function edit($id)
   {
    $user = User::findorfail($id);
    return view('pages.admin.user.edit', compact('user'));
   }

   public function update(Request $request, $id)
   {
    $user = User::findorfail($id);
    $input = $request->all();
    if($request->file('image')){
        $file= $request->file('image');
        $filename= date('YmdHis').'.'.$file->getClientOriginalExtension();
        $file-> move(public_path('/image'), $filename);
        $input['image']= $filename;
    }

    $user->update($input);

    return redirect()->route('admin.user.index')->with('success', 'Data berhasil di update');
    // return redirect()->back();
   }

   public function destroy(User $user)
   {

    $user->delete();

    return redirect()->route('admin.user.index')->with('success', 'Data berhasil di delete');
   }
}

resources/views/pages/admin/user/create.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Base Controls
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.user.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="mb-3">
                        <label for="image" class="form-label">Post Image</label>
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image" name="image" required>
                        @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                <div class="form-group">
                    <label>Name <span class="text-danger">*</span></label>
                    <input name="name" type="text" class="form-control" placeholder="Enter name" required />
                    @error('name')
                        <span class="form-text text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Email address <span class="text-danger">*</span></label>
                    <input name="email" type="email" class="form-control" placeholder="Enter email"  />
                    @error('email')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required />
                    @error('password')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
            </div>
            <div class="form-group mb-8">
                <div class="form-group">
                    <label>Phone <span class="text-danger">*</span></label>
                    <input name="phone" type="number" class="form-control" placeholder="Phone" required />
                    @error('phone')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
            </div>
            <div class="form-group mb-8">
                <div class="form-group">
                    <label>Address <span class="text-danger">*</span></label>
                    <input name="address" type="address" class="form-control" placeholder="Address" required />
                    @error('address')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
            </div>
            <div class="form-group mb-8">
                <div class="form-group">
                    <label>Birth Date <span class="text-danger">*</span></label>
                    <input name="birth_date" type="date" class="form-control" placeholder="Birth Date" required />
                    @error('birth_date')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
            </div>
            <div class="form-group mb-8">
                <div class="form-group">
                    <label>Birth Place <span class="text-danger">*</span></label>
                    <input name="birth_place" type="birthplace" class="form-control" placeholder="Birth Place" required />
                    @error('birth_place')
                    <span class="form-text text-danger">{{ $message }}</span>
                @enderror
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                <a class="btn btn-secondary" href="{{ route('admin.user.index') }}">Cancel</a>
            </div>
        </form>
        <!--end::Form-->
    </div>
@endsection

resources/views/pages/admin/user/edit.blade.php
@extends('layouts.admin.app')
@section('content')
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Base Controls
            </h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form action="{{ route('admin.user.update', $user->id) }}" method="POST" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="mb-3">
                        <label for="image" class="form-label">Post Image</label>
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image"
                            name="image" value="{{asset('image/'.$user->image) }}">
                        @error('image')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Name <span class="text-danger">*</span></label>
                        <input name="name" type="text" class="form-control" placeholder="Enter name"
                            value="{{ $user->name }}" />
                    </div>
                    <div class="form-group">
                        <label>Email address <span class="text-danger">*</span></label>
                        <input name="email" type="email" class="form-control" placeholder="Enter email"
                            value="{{ $user->email }}" />
                        <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1"
                            placeholder="Password" />
                    </div>
                </div>
                <div class="form-group mb-8">
                    <div class="form-group">
                        <label>Phone <span class="text-danger">*</span></label>
                        <input name="phone" type="number" class="form-control" placeholder="Phone"
                            value="{{ $user->phone }}" />
                    </div>
                </div>
                <div class="form-group mb-8">
                    <div class="form-group">
                        <label>Address <span class="text-danger">*</span></label>
                        <input name="address" type="address" class="form-control" placeholder="Address"
                            value="{{ $user->address }}" />
                    </div>
                </div>
                <div class="form-group mb-8">
                    <div class="form-group">
                        <label>Birth Date <span class="text-danger">*</span></label>
                        <input name="birt_date" type="date" class="form-control" placeholder="Birth Date"
                            value="{{ $user->birth_date }}" />
                    </div>
                </div>
                <div class="form-group mb-8">
                    <div class="form-group">
                        <label>Birth Place <span class="text-danger">*</span></label>
                        <input name="birth_place" type="birthplace" class="form-control" placeholder="Birth Place"
                            value="{{ $user->birth_place }}" />
                    </div>
                </div>
                <div class="form-group mb-8">
                    <div class="form-group">
                        <label>Jenis Kelamin<span class="text-danger">*</span></label>
                        <input name="jk" type="birthplace" class="form-control" placeholder="jk"
                            value="{{ $user->jk }}" />
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-success mr-2">Update</button>
                    <a class="btn btn-secondary" href="{{ route('admin.user.index') }}">Cancel</a>
                </div>
        </form>
        </form>
        <!--end::Form-->
    </div>
@stop

resources/views/pages/admin/user/index.blade.php
@extends('layouts.admin.app')
@section('content')
    {{-- <div>
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nis</th>
            <th>Nama</th>
            <th>Rombel</th>
            <th>Rayon</th>
            <th width="280px">Action</th>
        </tr>
</div> --}}
    <div class="card-header border-0 py-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label font-weight-bolder text-dark">Data User</span>
        </h3>
        <div class="card-toolbar">
            <a href="{{ route('admin.user.create') }}" class="btn btn-success font-weight-bolder font-size-sm">Create</a>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger">
            <p>{{ $message }}</p>
        </div>
    @endif
    <div class="card-header border-0 py-5">
        <div class="tab-content">
            <!--begin::Table-->
            <div class="table-responsive">
                <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                    <thead>
                        <tr class="text-left text-uppercase">
                            <th style="min-width: 80px">Image</th>
                            <th style="min-width: 80px">Name</th>
                            <th style="min-width: 100px">Email</th>
                            <th style="min-width: 100px">Phone</th>
                            <th style="min-width: 130px">Address</th>
                            <th style="min-width: 80px">Birth Date</th>
                            <th style="min-width: 80px">Birth Place</th>
                            <th style="min-width: 80px">Jenis Kelamin</th>
                            <th style="min-width: 80px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $data)
                            <tr>
                                @if (Auth::user()->id != $data->id)
                                <td><img src="{{ asset('image/'.$data->image) }}" class="card-img" height="100" alt="" /></td>
                                <td>{{ $data->name }}</td>
                                <td>{{ $data->email }}</td>
                                <td>{{ $data->phone }}</td>
                                <td>{{ $data->address }}</td>
                                <td>{{ $data->birth_date }}</td>
                                <td>{{ $data->birth_place }}</td>
                                <td>{{$data->jk}}</td>
                                <td>
                                    <a class="btn btn-sm btn-primary" href="{{ route('admin.user.edit', $data->id) }}">Edit</a>
                                    <form action="{{ route('admin.user.destroy', $data->id) }}" method="POST"
                                        class="d-inline">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                    {{-- <div class="row">
                                        <div class="col-6">
                                            <a class="btn btn-primary"
                                                href="{{ route('admin.user.edit', $data->id) }}">Edit</a>
                                        </div>
                                        <div class="col-6">
                                            <form action="{{ route('admin.user.destroy', $data->id) }}" method="POST"
                                                class="d-inline">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </td> --}}
                            </tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!--end::Table-->
        </div>
    </div>
    {{-- <div class="card card-custom">
    <div class="card-header">
     <h3 class="card-title">
      Textual HTML5 Inputs
     </h3>
    </div>
    <!--begin::Form-->
    <form>
     <div class="card-body">
      <div class="form-group mb-8">
      <div class="form-group row">
       <label  class="col-2 col-form-label">Name</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-text-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-search-input" class="col-2 col-form-label">Email</label>
       <div class="col-10">
        <input class="form-control" type="search" id="example-search-input"/>
       </div>
      </div>
      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Password</label>
        <div class="col-10">
         <input class="form-control" type="password" id="example-password-input"/>
        </div>
       </div>
      <div class="form-group row">
       <label for="example-tel-input" class="col-2 col-form-label">Phone</label>
       <div class="col-10">
        <input class="form-control" type="tel" id="example-tel-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-password-input" class="col-2 col-form-label">Address</label>
       <div class="col-10">
        <input class="form-control" type="password"id="example-password-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-date-input" class="col-2 col-form-label">Birth Date</label>
       <div class="col-10">
        <input class="form-control" type="date" id="example-date-input"/>
       </div>
      </div>
      <div class="form-group row">
       <label for="example-month-input" class="col-2 col-form-label">Birth Place</label>
       <div class="col-10">
        <input class="form-control" type="text" id="example-month-input"/>
       </div>
      </div>
     </div>
     <div class="card-footer">
      <div class="row">
       <div class="col-2">
       </div>
       <div class="col-10">
        <button type="reset" class="btn btn-success mr-2">Submit</button>
        <button type="reset" class="btn btn-secondary">Cancel</button>
       </div>
      </div>
     </div>
    </form>
   </div>
</div> --}}
@stop